"""
Django settings for bookingSysterm project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys,datetime
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 添加导包路径

sys.path.insert(0,os.path.join(BASE_DIR,'users'))
# print(sys.path)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7e&-rc(ku-i33k*%0+5ftqlk7)foz)+*ilebu1susbef#7454o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1","183.6.116.44","*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'users.apps.UsersConfig',
    'infos.apps.InfosConfig',
    'experiments.apps.ExperimentsConfig',
    'courses.apps.CoursesConfig',
    # 允许跨域
    'corsheaders',
    'rest_framework',
    'django_crontab',  # 定时任务

    # 配置后台管理系统
    'xadmin',
    'crispy_forms',
    'reversion',
    'DjangoUeditor',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'bookingSysterm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookingSysterm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

class DBS():
    def __init__(self,DEBUG):
        self.DEBUG=DEBUG
        self.formal_db = {
            "ENGINE": "django.db.backends.mysql",
            "HOST": os.getenv("MYSQL_HOST", "172.99.0.4"),
            "PORT": os.getenv("MYSQL_PORT", 3306),
            "USER": os.getenv("MYSQL_USER", "root"),
            "PASSWORD": os.getenv("MYSQL_PWD", "0.0010.0"),
            "NAME": os.getenv("MYSQL_NAME", "yeslab_db"),
        }
        self.test_db = {
            "ENGINE": "django.db.backends.mysql",
            "HOST": os.getenv("MYSQL_HOST", "192.168.92.149"),
            "PORT": os.getenv("MYSQL_PORT", 3306),
            "USER": os.getenv("MYSQL_USER", "root"),
            "PASSWORD": os.getenv("MYSQL_PWD", "mysql"),
            "NAME": os.getenv("MYSQL_NAME", "userinfo"),
        }

    def default_db(self):
        if self.DEBUG:
            return self.test_db
        else:
            return self.formal_db

dbs = DBS(DEBUG)

DATABASES = {
    "default": dbs.default_db()
}


uri = os.getenv("REDIS_URI", "redis://192.168.92.149:6379")
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "%s/0"%os.getenv("REDIS_URI",uri),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "session": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "%s/1"%os.getenv("REDIS_URI",uri),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "verify": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "%s/2"%os.getenv("REDIS_URI",uri),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "email": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "%s/3"%os.getenv("REDIS_URI",uri),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}



# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,"static")

MEDIA_URL = "/static/media/"
MEDIA_ROOT = os.path.join(BASE_DIR,"static/media")

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}

JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=1),
}

# 定时任务
"""
* * * * *
分 时 日 月 周      命令
M: 分钟（0-59）。每分钟用*或者 */1表示
H：小时（0-23）。（0表示0点）
D：天（1-31）。
m: 月（1-12）。
d: 一星期内的天（0~6，0为星期天）。
"""
# CRONJOBS = [
#     # 每天０点执行一次
#     ('* 0 1 * *', 'scripts.gen_reservation_table.main','>>/home/python/Desktop/yeslab-booking-systerm/backend/logs/generate.log')
# ]

# 解决crontab中文问题
# CRONTAB_COMMAND_PREFIX = 'LANG_ALL=zh_cn.UTF-8'

# 邮件设置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.exmail.qq.com'
EMAIL_PORT = 465
#发送邮件的邮箱
EMAIL_HOST_USER = 'Chensy@yeslab.net'
#在邮箱中设置的客户端授权密码
EMAIL_HOST_PASSWORD = 'Csy727167175'
#收件人看到的发件人
EMAIL_FROM = 'python<admin@yeslab.net>'


# 权限认证
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',   # 基本认证
        # 'rest_framework.authentication.SessionAuthentication',  # session认证
    )
}




LOGGING = {
    'version': 1,  # 指明dictConnfig的版本，目前就只有一个版本，哈哈
    'disable_existing_loggers': False,  # 表示是否禁用所有的已经存在的日志配置
    'formatters': {  # 格式器
        'verbose': {  # 详细
            'format': '[%(levelname)s] [%(asctime)s] [%(module)s] [%(lineno)d] %(message)s'
        },
        'standard': {  # 标准
            'format': '[%(asctime)s] [%(levelname)s] %(message)s'
        },
    },
    # handlers：用来定义具体处理日志的方式，可以定义多种，"default"就是默认方式，"console"就是打印到控制台方式。file是写入到文件的方式，注意使用的class不同
    'handlers': { # 处理器，在这里定义了三个个处理器
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',  # 将日志消息发送到Stream。
            'formatter': 'standard'   # 制定输出的格式，注意 在上面的formatters配置里面选择一个，否则会报错
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',    # 将日志消息发送到磁盘文件，默认情况下文件大小会无限增长。
            'filename': os.path.join(BASE_DIR,'log/error.log'),  #记录错误日志
            'encoding': "utf-8",
            'formatter': 'verbose'
        },
        'default': {
            'level':'INFO',
            'class':'logging.handlers.RotatingFileHandler',    # 将日志消息发送到磁盘文件，并支持日志文件按大小切割。
            'filename': os.path.join(BASE_DIR,'log/all.log'),     #所有日志输出文件
            'encoding': "utf-8",
            'maxBytes': 1024*1024*5,                  #文件大小
            'backupCount': 5,                         #备份份数
            'formatter':'verbose',                   #使用哪种formatters日志格式
        },
        # 上面两种写入日志的方法是有区别的，前者是将控制台下输出的内容全部写入到文件中，这样做的好处就是我们在views代码中的所有print也会写在对应的位置
        # 第二种方法就是将系统内定的内容写入到文件，具体就是请求的地址、错误信息等，小伙伴也可以都使用一下然后查看两个文件的异同。
    },
    'loggers': {  # log记录器，配置之后就会对应的输出日志
        # django 表示就是django本身默认的控制台输出，就是原本在控制台里面输出的内容，在这里的handlers里的file表示写入到上面配置的file-/home/aea/log/jwt_test.log文件里面
        # 在这里的handlers里的console表示写入到上面配置的console-/home/aea/log/test.log文件里面
        'django': {
            'handlers': ['console','file','default'], # 同时输出到对应的三个处理器中
            'level': 'DEBUG',    # 此处指定的级别以上才会进入到指定的处理器
            'propagate': True,
        },
        # 'django.request ':{
        #     'handlers': ['console','file'],
        #     'level': 'WARNING',  # 配合上面的将警告log写入到另外一个文件
        #     'propagate': True,
        # },
        # 'django.db.backends': {
        #     'handlers': ['file'], # 指定file handler处理器，表示只写入到文件
        #     'level':'DEBUG',
        #     'propagate': True,
        # },
    },
}
