# Generated by Django 2.1.4 on 2019-10-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_userinfo'),
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='开放预约日期')),
                ('tb_id', models.SmallIntegerField(choices=[(1, '上午'), (2, '下午'), (3, '晚上')], verbose_name='开放面试时段')),
                ('num', models.SmallIntegerField(default=6, verbose_name='可预约人数')),
                ('comment', models.CharField(blank=True, default='', max_length=50, verbose_name='备注说明(选填)')),
                ('user', models.ManyToManyField(blank=True, null=True, to='users.UserInfo', verbose_name='预约学生(选填)')),
            ],
            options={
                'verbose_name': '面试预约信息表',
                'verbose_name_plural': '面试预约信息表',
                'db_table': 'interview',
            },
        ),
    ]
